google_analytics: ""
plugins:
  - jekyll-feed
twitter_username: iotapublications
collections_dir: _collections
include:
  - _pages
author: Iota Publications
email: iotapublications@gmail.com
description: This is the description of my site. For all intents and purposes,
  it's complete.
tagline: Hi! We're Iota.
markdown: kramdown
url: https://iota.gq
github_username: iotapublications
collections:
  authors:
    output: true
  history:
    output: true
  politics:
    output: true
  science:
    output: true
title: Iota
image: https://www.simplek12.com/wp-content/uploads/2015/07/shutterstock_173128658.jpg
baseurl: ""
